- name: Create a downloads directory if it does not exist
  file:
    path: "{{downoads_base_path}}/{{downloads_dir}}"
    state: directory
  tags: 
    - never
    - install

- name: Create a series directory if it does not exist
  file:
    path: "{{series_base_path}}/{{series_dir}}"
    state: directory
  tags: 
    - never
    - install  

- name: Create a movies directory if it does not exist
  file:
    path: "{{default_base_path}}/{{movies_dir}}"
    state: directory
  tags: 
    - never
    - install       

- name: Create a config directory if it does not exist
  file:
    path: "{{config_base_path}}/{{config_dir}}"
    state: directory
  tags: 
    - never
    - install      
          
- name: Create a sub config directory if it does not exist
  file:
    path: "{{config_base_path}}/{{config_dir}}/{{item}}"
    state: directory
  loop: "{{ config_folders }}"
  tags: 
    - never
    - install      
