- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Upgrade the OS (apt-get dist-upgrade)
  apt:
    upgrade: dist

- name: Install required system packages
  apt:
    pkg:
      - vim
      - curl
    state: latest

- name: Install Pip packages
  apt:
    pkg:
      - python3-pip
      - python3-setuptools
      - python3-dev
      - libffi-dev
      - libssl-dev
    state: latest