- docker_compose:
    pull: "{{docker_pull}}"
    recreate: "{{docker_recreate}}"
    project_name: downloadServer
    definition:
      version: "2.1"
      services:
        plex:
          image: "linuxserver/plex:{{image_version}}"
          container_name: plex
          network_mode: host
          environment:
            - PUID=1000
            - PGID=1000
            - VERSION=docker
            - TZ="{{time_zone}}"
          volumes:
            - "{{config_base_path}}/{{config_dir}}/plex:/config"
            - "{{series_base_path}}/{{series_dir}}:/tv"
            - "{{movies_base_path}}/{{movies_dir}}:/movies"
          restart: unless-stopped
  tags: 
    - install      
    - update  
    - rebuild 

          