- name: Install Docker Module for Python
  pip:
    name:
      - docker
      - docker-compose 
  tags: 
    - never
    - install      
    - upgrade    
    - rebuild    

- name: source bashrc
  ansible.builtin.shell: source ~/.bashrc
  args:
    executable: /bin/bash
  tags: 
    - never
    - install    

- name: Start container 
  include_tasks: "{{item}}.yml"
  loop: "{{docker_containers}}"
  tags: 
    - never
    - install      
    - upgrade    
    - rebuild