- name: Install Docker Module for Python
  pip:
    name:
      - docker
      - docker-compose 
  tags: 
    - never
    - install      
    - update    
    - rebuild    

- name: Run docker without relogging
  ansible.builtin.shell: exec su -l {{current_user}}
  args:
    executable: /bin/bash
  tags: 
    - never
    - install    

- name: Start container 
  include_tasks: "{{item}}.yml"
  loop: "{{docker_containers}}"
  tags: 
    - never
    - install      
    - update    
    - rebuild