- docker_compose:
    project_name: downloadServer
    definition:
      version: "2.1"
      services:
        nzbhydra2:
          image: "linuxserver/nzbhydra2:{{image_version}}"
          container_name: nzbhydra2
          environment:
            - PUID=1000
            - PGID=1000
            - TZ="{{time_zone}}"
          volumes:
            - "{{base_path}}/{{config_dir}}/nzbhydra2:/config"
          ports:
            - 5076:5076
          restart: unless-stopped
          mem_limit: 512M
          mem_reservation: 512M
          logging:
            driver: "json-file"
            options:
              max-size: "256m"          
