- name: Create qbittorrent container
  docker_compose:
    pull: "{{docker_pull}}"
    recreate: "{{docker_recreate}}"
    project_name: downloadServer
    definition:
      version: "2.1"
      services:
        qbittorrent:
          image: "linuxserver/qbittorrent:{{image_version}}"
          container_name: qbittorrent
          environment:
            - PUID=1000
            - PGID=1000
            - TZ="{{time_zone}}"
            - UMASK_SET=022
            - WEBUI_PORT=8080
          volumes:
            - "{{config_base_path}}/{{config_dir}}/qbittorrent:/config"
            - "{{downoads_base_path}}/{{downloads_dir}}:/downloads"
          ports:
            - 6881:6881
            - 6881:6881/udp
            - 8080:8080
          restart: unless-stopped
          mem_limit: 1024M
          mem_reservation: 512M
          logging:
            driver: "json-file"
            options:
              max-size: "256m"          
  tags: 
    - never
    - install      
    - update    
    - rebuild             
