- name: Create radarr container
  docker_compose:
    pull: "{{docker_pull}}"
    recreate: "{{docker_recreate}}"
    project_name: downloadServer
    definition:
      version: "2.1"
      services:
        radarr:
          image: "linuxserver/radarr:{{image_version}}"
          container_name: radarr
          environment:
            - PUID=1000
            - PGID=1000
            - TZ="{{time_zone}}"
          volumes:
            - "{{config_base_path}}/{{config_dir}}/radarr:/config"
            - "{{movies_base_path}}/{{movies_dir}}:/movies"
            - "{{downoads_base_path}}/{{downloads_dir}}:/downloads"
          ports:
            - 7878:7878
          restart: unless-stopped
          mem_limit: 1024M
          mem_reservation: 512M
          logging:
            driver: "json-file"
            options:
              max-size: "256m"          
  tags: 
    - never
    - install      
    - upgrade   
    - rebuild              
