- docker_compose:
    project_name: downloadServer
    definition:
      version: "2.1"
      services:
        sonarr:
          image: "linuxserver/sonarr:{{image_version}}"
          container_name: sonarr
          environment:
            - PUID=1000
            - PGID=1000
            - TZ="{{time_zone}}"
            - UMASK_SET=022 #optional
          volumes:
            - "{{base_path}}/{{config_dir}}/sonarr:/config"
            - "{{base_path}}/{{series_dir}}:/tv"
            - "{{base_path}}/{{downloads_dir}}:/downloads"
          ports:
            - 8989:8989
          restart: unless-stopped