---
version: "2.1"
services:
  sonarr:
    image: linuxserver/sonarr:arm32v7-latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
      - UMASK_SET=022 #optional
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${SERIES_DIR}:/tv
      - ${DOWNLOAD_DIR}:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett:arm32v7-latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
    volumes:
      - ${CONFIG_DIR}/jackett:/config
    ports:
      - 9117:9117
    restart: unless-stopped
  # any torrnet client can be used. 
  qbittorrent:
    image: linuxserver/qbittorrent:arm32v7-latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Johannesburg
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - ${CONFIG_DIR}/qbittorrent:/config
      - ${DOWNLOAD_DIR}:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
  # nzbhydra2 not needed just a nice to have.
  nzbhydra2:
    image: linuxserver/nzbhydra2:arm32v7-latest
    container_name: nzbhydra2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
    volumes:
      - ${CONFIG_DIR}/nzbhydra2:/config
    ports:
      - 5076:5076
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr:arm32v7-latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${MOVIE_DIR}:/movies
      - ${DOWNLOAD_DIR}:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped