- docker_compose:
    project_name: downloadServer
    definition:
      version: "2.1"
      services:
        nginx:
          build: .
          container_name: nginx
          restart: unless-stopped