- name: Copy home-page data
  copy:
    src: ./nginx
    dest: "{{config_base_path}}/{{config_dir}}/"
  tags: 
    - never
    - install   
- docker_compose:
    project_name: downloadServer
    definition:
      version: "2.1"
      services:
        nginx:
          image: linuxserver/nginx
          container_name: nginx
          restart: unless-stopped
          volumes:
            - "{{config_base_path}}/{{config_dir}}/nginx/www:/config/www"
            - "{{config_base_path}}/{{config_dir}}/nginx/config:/config/nginx/site-confs"
          ports:
            - 80:80  
          mem_limit: 64m
          mem_reservation: 32M
          cpus: 0.1  
          logging:
            driver: "json-file"
            options:
              max-size: "256m"          
  tags: 
    - never
    - install