- name: Install Docker Module for Python
  pip:
    name:
      - docker
      - docker-compose 

- docker_compose:
    project_name: downloadServer
    definition:
      version: "2.1"
      services:
        sonarr:
          image: "linuxserver/sonarr:{{image_version}}"
          container_name: sonarr
          environment:
            - PUID=1000
            - PGID=1000
            - TZ="{{time_zone}}"
            - UMASK_SET=022 #optional
          volumes:
            - "{{base_path}}/{{config_dir}}/sonarr:/config"
            - "{{base_path}}/{{series_dir}}:/tv"
            - "{{base_path}}/{{downloads_dir}}:/downloads"
          ports:
            - 8989:8989
          restart: unless-stopped
        jackett:
          image: "linuxserver/jackett:{{image_version}}"
          container_name: jackett
          environment:
            - PUID=1000
            - PGID=1000
            - TZ="{{time_zone}}"
          volumes:
            - "{{base_path}}/{{config_dir}}/jackett:/config"
          ports:
            - 9117:9117
          restart: unless-stopped
        qbittorrent:
          image: "linuxserver/qbittorrent:{{image_version}}"
          container_name: qbittorrent
          environment:
            - PUID=1000
            - PGID=1000
            - TZ="{{time_zone}}"
            - UMASK_SET=022
            - WEBUI_PORT=8080
          volumes:
            - "{{base_path}}/{{config_dir}}/qbittorrent:/config"
            - "{{base_path}}/{{downloads_dir}}:/downloads"
          ports:
            - 6881:6881
            - 6881:6881/udp
            - 8080:8080
          restart: unless-stopped
        nzbhydra2:
          image: "linuxserver/nzbhydra2:{{image_version}}"
          container_name: nzbhydra2
          environment:
            - PUID=1000
            - PGID=1000
            - TZ="{{time_zone}}"
          volumes:
            - "{{base_path}}/{{config_dir}}/nzbhydra2:/config"
          ports:
            - 5076:5076
          restart: unless-stopped
        radarr:
          image: "linuxserver/radarr:{{image_version}}"
          container_name: radarr
          environment:
            - PUID=1000
            - PGID=1000
            - TZ="{{time_zone}}"
          volumes:
            - "{{base_path}}/{{config_dir}}/radarr:/config"
            - "{{base_path}}/{{movies_dir}}:/movies"
            - "{{base_path}}/{{downloads_dir}}:/downloads"
          ports:
            - 7878:7878
          restart: unless-stopped
  # register: output
# - debug:
#     var: output

# - assert:
#     that:
#       - "sonarr.sonarr.state.running"
#       - "jackett.jackett.state.running"
#       - "qbittorrent.qbittorrent.state.running"
#       - "nzbhydra2.nzbhydra2.state.running"
#       - "radarr.radarr.state.running"
      