- name: Setting up media server
  hosts: localhost
  remote_user: user
  tasks:
    - name: Download .sh File
      ansible.builtin.get_url:
        url: https://get.docker.com
        dest: /tmp/docker.sh

    - name: Run .sh File
      ansible.builtin.shell:
        cmd: cat /tmp/docker.sh | sh -s -- -y

    - name: Setting up docker to work without sudo
      become: yes
      become_method: sudo
      ansible.builtin.shell: groupadd docker

    - name: Setting up docker to work without sudo
      become: yes
      become_method: sudo
      ansible.builtin.shell: usermod -aG docker $USER
