- name: Setting up media server
  hosts: localhost
  remote_user: user
  
  roles:
    - setup
    - folders
    - samba
    - staticIP
    - docker

# Install Sonarr, radarr, Jackett, qbittorrent and nzbhydra
