- name: Setting up media server
  hosts: localhost
  remote_user: user

  vars:
    base_path: "{{default_base_path | default('/tmp/downloadServer')}}"
    time_zone: "{{ ansible_env.TZ | default('Europe/London') }}"
    docker_pull: 'false'
    docker_recreate: "smart"
    ip_address: "{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}"
    current_user: "{{ lookup('env', 'USER') }}"
    distro: "{{ ansible_distribution }}"
    distro_releases:
      "22": jammy
      "21": impish
      "20": focal
      "18": bionic
      default: "{{ ansible_distribution_release }}"
    distro_release: "{{ distro_releases[ansible_distribution_major_version | default('default')] }}"
    ansible_os_family: Debian
    pip_install_packages:
      - name: docker
        
  roles:
    - setup
    - geerlingguy.pip
    - role: geerlingguy.docker
      tags:
        - docker
        - install
        - rebuild
      become: true
      docker_edition: 'ce'
      docker_apt_repository: "deb [arch={{ docker_apt_arch }}] {{ docker_repo_url }}/{{ distro | lower }} {{ distro_release }} {{ docker_apt_release_channel }}"
      docker_apt_gpg_key: "{{ docker_repo_url }}/{{ distro | lower }}/gpg"
      docker_service_manage: true
      docker_service_state: started
      docker_service_enabled: true
      docker_install_compose_plugin: true
      docker_compose_package: docker-compose-plugin
      docker_compose_package_state: present
      docker_users:
      - "{{ current_user }}"

    - folders
    - containers
    - home-page
    - plex
    - post-setup
